### PR TITLE
Check for existence of "screen" global before using

### PR DESCRIPTION
**Pull request by gabrielgrant**
This is needed to be able to import with node/build with ember-cli

fixes immersive-web/webvr-polyfill#322
replaces https://github.com/immersive-web/webvr-polyfill/pull/323

### CODE REVIEW

**Comment by gabrielgrant** [comment]
@jsantell any more thoughts about getting this merged in? I'm currently using my patched version of the compiled source in webvr-polyfill, which is working fine for me at the moment, but I'd really rather not have to maintain that longer term

**Comment by gabrielgrant** [comment]
for more context/history, @kellyselden commented to link to his previous fixes here: https://github.com/immersive-web/webvr-polyfill/issues/322#issuecomment-392896564

**Comment by jsantell** [comment]
@gabrielgrant sorry for the wait on this! I just submitted #28 which removes the need for screen orientation entirely which will help here as well

**Comment by gabrielgrant** [comment]
Thanks for the follow-up!

**Comment by jsantell** [comment]
Landed #28, will uplift in the next version of webvr-polyfill!

**Pull request closed without merging**
